### ISSUE TITLE
Getting White Blank page

### ISSUE THREAD

**Issue by VedantSugandhi** [RiadhAdrani/slick-portfolio-svelte#46]
Hello Riadh,

i am getting a white blank page, dont know why, will appreciate your help.

below is my github repo link
https://github.com/VedantSugandhi/vsPF

thanks in advance
Vedant

**Comment by RiadhAdrani** [comment]
Hello @VedantSugandhi,

It seems that your base is not setup correctly [here](https://github.com/VedantSugandhi/vsPF/blob/4a8a119a8b17dea76c6da4fb147b9b0c544b2eb7/svelte.config.js#L4) 

it should be `const base = "/vsPF"`

Let me know if that fixed the issue.

**Comment by VedantSugandhi** [comment]
I tried by giving this base as well but it's not working. Same white blank page is coming.

**Comment by RiadhAdrani** [comment]
set it to `/vsPF` and it will work, try hard refreshing or wait for some minutes, it will update.

**Comment by VedantSugandhi** [comment]
Hii Riadh,

Still, the issue persists.

Let me know when is a good time to connect with you, if possible for you, we can hop on Zoom.

**Comment by RiadhAdrani** [comment]
@VedantSugandhi 

The workflow is not running, because it build from the `main` branch, which does not exist, [change it to `master`](https://github.com/VedantSugandhi/vsPF/blob/4ec4823fda7bb8761fb689944a58716e6767b1e7/.github/workflows/deploy.yml#L5)

Also, I forked your repo and make it work : 

repo : https://github.com/RiadhAdrani/vsPF
page : https://riadhadrani.github.io/vsPF

**Comment by VedantSugandhi** [comment]
Thanks, Riadh, for helping me out with this, it's a very pity mistake, I don't know how it got missed by me. this issue taught me lot of things on yaml & deployment side.

Your template is very amazing.

Thank you again for helping me out.
