### ISSUE TITLE
Can't clone or host page

### ISSUE THREAD

**Issue by alessioamo** [RiadhAdrani/slick-portfolio-svelte#9]
Hello, I tried to clone the repository and that didn't work, I was met with this error.

Cloning into '\slick-portfolio-svelte'...
remote: Enumerating objects: 2461, done.        
remote: Counting objects: 100% (825/825), done.        
remote: Compressing objects: 100% (302/302), done.        
remote: Total 2461 (delta 744), reused 523 (delta 523), pack-reused 1636        
Receiving objects: 100% (2461/2461), 2.86 MiB | 1.65 MiB/s, done.
Resolving deltas: 100% (1394/1394), done.
error: invalid path 'static/riadh_circle.ico:Zone.Identifier'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

Alternatively, I tried to manually download the repo and push it on its own, but even though I changed the base parameter in svelte.config.js, my page just loads the readme (see link below)

https://alessioamo.github.io/slick-portfolio-svelte-master/

**Comment by RiadhAdrani** [comment]
Hello,
I removed the file, hoping that it fixes the problems with cloning.

Now, make sure to follow these steps :
- make sure to enable github actions with the correct permissions :
   - go to your repo `Settings` > `Actions` > `General` :
       - Actions permissions : check `Allow all actions and reusable workflows`
       - Workflow permissions : check `Read repository contents and packages permissions`
- you cloned the repo with `main` as the main branch, change the target branch in [`deploy.yml`](https://github.com/RiadhAdrani/slick-portfolio-svelte/blob/31bc1621009c60d77ef197b420a18b2f996876a9/.github/workflows/deploy.yml#L5) to `main`. 
- push changes to run the action with new settings and permissions, or create an empty commit and push it if you didn't change anything.
- enable `GitHub Pages` deployment on the newly created `gh-pages` branch:
    - go to your repo's `Settings` > `Pages`
        - Source : select `Deploy from a branch`
        - Branch : select `gh-pages` and `/ (root)` and click on `save`
- wait for the page to be deployed

Here's a working clone of your repo:
https://riadhadrani.github.io/alessioamo-slick-portfolio-svelte-master

Tell if your problem was fixed.
All the best.

**Comment by alessioamo** [comment]
Thanks for the quick reply!
I made all the changes but for some reason, my link keeps opening to the readme file

**Comment by RiadhAdrani** [comment]
@alessioamo are you sure, you waited long enough ? 
https://alessioamo.github.io/slick-portfolio-svelte-master

**Comment by alessioamo** [comment]
Hm, I waited a few minutes but I guess it wasn't long enough, it works thank you!
